services:
  - type: web
    name: streamlit-app
    env: python
    plan: free
    runtime: python-3.10.14
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
